/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.vistas;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import modulo.estructuras.ColaPrioridadHospital;
import modulo.modelo.Paciente;

/**
 *
 * @author paula
 */
public class VentanaHospital extends javax.swing.JFrame {
    private ColaPrioridadHospital colaTriaje;
    private VentanaMenuHospital menuPrincipal;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaHospital.class.getName());

    /**
     * Creates new form VentanaHospital
     */
    public VentanaHospital(VentanaMenuHospital menuShared, modulo.estructuras.ColaPrioridadHospital colaShared) {
        initComponents();
        this.menuPrincipal = menuShared;
        this.colaTriaje = colaShared;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboPrioridad = new javax.swing.JComboBox<>();
        btnRegistrarTurno = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        txtCedula.setBorder(null);

        txtNombre.setBorder(null);

        cboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nivel de triaje", "1 - Paro Médico", "2 - Urgencia Alta", "3 - Urgencia Media", "4 - Urgencia Menor", "5 - Consulta General" }));
        cboPrioridad.addActionListener(this::cboPrioridadActionPerformed);

        btnRegistrarTurno.setBorderPainted(false);
        btnRegistrarTurno.setContentAreaFilled(false);
        btnRegistrarTurno.addActionListener(this::btnRegistrarTurnoActionPerformed);

        btnVolverMenu.setBorder(null);
        btnVolverMenu.setContentAreaFilled(false);
        btnVolverMenu.addActionListener(this::btnVolverMenuActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(cboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRegistrarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                .addComponent(btnVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(cboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 620, 360));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo_RegPacientes.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 680, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPrioridadActionPerformed

    private void btnRegistrarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTurnoActionPerformed
        // TODO add your handling code here:
        String cedula = txtCedula.getText().trim();
        String nombre = txtNombre.getText().trim();
        
        // Obtenemos el índice del ComboBox
        int seleccionPrioridad = cboPrioridad.getSelectedIndex();

        if (cedula.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese la identificación y el nombre completo.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (seleccionPrioridad == 0) {
            JOptionPane.showMessageDialog(this, "Debe asignar un nivel de prioridad de triaje.", "Falta Nivel de Triaje", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int nivelTriaje = seleccionPrioridad; 
        String prioridadTexto = cboPrioridad.getSelectedItem().toString();

        // Creamos el objeto Paciente e insertamos en tu cola enlazada ordenada
        Paciente nuevoPaciente = new Paciente(cedula, nombre, nivelTriaje);
        colaTriaje.insertar(nuevoPaciente);

        // Persistencia en archivo de texto de respaldo
        try (FileWriter fw = new FileWriter("pacientes_triaje.txt", true);
             BufferedWriter bw = new BufferedWriter(fw);
             PrintWriter out = new PrintWriter(bw)) {
            
            out.println(cedula + "," + nombre + "," + prioridadTexto);
            
            JOptionPane.showMessageDialog(this, 
                    "Paciente ingresado con éxito.\n¡Tu estructura interna lo ordenó por prioridad!", 
                    "Registro Exitoso", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            // Limpieza de los campos para el siguiente registro
            txtCedula.setText("");
            txtNombre.setText("");
            cboPrioridad.setSelectedIndex(0);

        } catch (IOException e) {
            System.out.println("Error de persistencia: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnRegistrarTurnoActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:
        this.menuPrincipal.setVisible(true); // Reaparece el menú original con los datos intactos
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTurno;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JComboBox<String> cboPrioridad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
