/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.vistas;

import modulo.estructuras.ColaPrioridadHospital;
import modulo.servicios.ListaHistorialAtendidos;

/**
 *
 * @author paula
 */
public class VentanaMenuHospital extends javax.swing.JFrame {
    private ColaPrioridadHospital colaTriaje;
    private ListaHistorialAtendidos historialAtendidos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMenuHospital.class.getName());

    /**
     * Creates new form VentanaMenuHospital
     */
    public VentanaMenuHospital() {
        initComponents();
        this.colaTriaje = new ColaPrioridadHospital();
        this.historialAtendidos = new ListaHistorialAtendidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevoIngreso = new javax.swing.JButton();
        btnLlamarPaciente = new javax.swing.JButton();
        btnBusquedaCritica = new javax.swing.JButton();
        btnReportesDia = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        btnNuevoIngreso.setBorder(null);
        btnNuevoIngreso.setBorderPainted(false);
        btnNuevoIngreso.setContentAreaFilled(false);
        btnNuevoIngreso.addActionListener(this::btnNuevoIngresoActionPerformed);

        btnLlamarPaciente.setBorder(null);
        btnLlamarPaciente.setBorderPainted(false);
        btnLlamarPaciente.setContentAreaFilled(false);
        btnLlamarPaciente.addActionListener(this::btnLlamarPacienteActionPerformed);

        btnBusquedaCritica.setBorder(null);
        btnBusquedaCritica.setBorderPainted(false);
        btnBusquedaCritica.setContentAreaFilled(false);
        btnBusquedaCritica.addActionListener(this::btnBusquedaCriticaActionPerformed);

        btnReportesDia.setBorder(null);
        btnReportesDia.setBorderPainted(false);
        btnReportesDia.setContentAreaFilled(false);
        btnReportesDia.addActionListener(this::btnReportesDiaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLlamarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnBusquedaCritica, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnReportesDia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBusquedaCritica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLlamarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportesDia, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 770, 300));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo_nuevoMenu.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 830, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoIngresoActionPerformed
        // TODO add your handling code here:
        VentanaHospital formularioRegistro = new VentanaHospital(this, this.colaTriaje);
        // Mostramos el formulario de registro
        formularioRegistro.setVisible(true);
        // Ocultamos el menú principal temporalmente
        this.setVisible(false);
    }//GEN-LAST:event_btnNuevoIngresoActionPerformed

    private void btnLlamarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlamarPacienteActionPerformed
        // TODO add your handling code here:
        VentanaAtencion pantallaAtencion = new VentanaAtencion(this, this.colaTriaje, this.historialAtendidos);
        pantallaAtencion.setVisible(true);
        // Ocultamos el menú principal temporalmente
        this.setVisible(false);
    }//GEN-LAST:event_btnLlamarPacienteActionPerformed

    private void btnBusquedaCriticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaCriticaActionPerformed
        // TODO add your handling code here:
        
        VentanaBusqueda pantallaBusqueda = new VentanaBusqueda(this, this.colaTriaje, this.historialAtendidos);
        pantallaBusqueda.setVisible(true);
    
        // Ocultamos el menú principal
        this.setVisible(false);
    }//GEN-LAST:event_btnBusquedaCriticaActionPerformed

    private void btnReportesDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaMenuHospital().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaCritica;
    private javax.swing.JButton btnLlamarPaciente;
    private javax.swing.JButton btnNuevoIngreso;
    private javax.swing.JButton btnReportesDia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
