/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.vistas;

import modulo.estructuras.ColaPrioridadHospital;
import modulo.servicios.ListaHistorialAtendidos;

/**
 *
 * @author paula
 */
public class VentanaMenuHospital extends javax.swing.JFrame {
    private ColaPrioridadHospital colaTriaje;
    private ListaHistorialAtendidos historialAtendidos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMenuHospital.class.getName());

    /**
     * Creates new form VentanaMenuHospital
     */
    public VentanaMenuHospital() {
        initComponents();
        this.colaTriaje = new ColaPrioridadHospital();
        this.historialAtendidos = new ListaHistorialAtendidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevoRegistro = new javax.swing.JButton();
        btnIniciarAtencion = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        btnNuevoRegistro.setBorder(null);
        btnNuevoRegistro.setBorderPainted(false);
        btnNuevoRegistro.setContentAreaFilled(false);
        btnNuevoRegistro.addActionListener(this::btnNuevoRegistroActionPerformed);

        btnIniciarAtencion.setBorder(null);
        btnIniciarAtencion.setBorderPainted(false);
        btnIniciarAtencion.setContentAreaFilled(false);
        btnIniciarAtencion.addActionListener(this::btnIniciarAtencionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnIniciarAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIniciarAtencion, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnNuevoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 410, 320));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo_menuPrincipal.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 590, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRegistroActionPerformed
        // TODO add your handling code here:
        VentanaHospital formularioRegistro = new VentanaHospital(this, this.colaTriaje);
        formularioRegistro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNuevoRegistroActionPerformed

    private void btnIniciarAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarAtencionActionPerformed
        // TODO add your handling code here:
        //VentanaAtencion pantallaEspera = new VentanaAtencion(this, this.colaTriaje, this.historialAtendidos);
        //pantallaEspera.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnIniciarAtencionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaMenuHospital().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarAtencion;
    private javax.swing.JButton btnNuevoRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
