/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.vistas;

import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import modulo.estructuras.ColaPrioridadHospital;
import modulo.modelo.Paciente;
import modulo.servicios.GestorAlgoritmos;
import modulo.servicios.ListaHistorialAtendidos;
/**
 *
 * @author paula
 */
public class VentanaBusqueda extends javax.swing.JFrame {
    private ColaPrioridadHospital colaTriaje;
    private ListaHistorialAtendidos historialAtendidos;
    private VentanaMenuHospital menuPrincipal;
    

    /**
     * Creates new form VentanaBusqueda
     * @param menuShared
     * @param colaShared
     * @param historialShared
     */
    public VentanaBusqueda(VentanaMenuHospital menuShared, ColaPrioridadHospital colaShared, ListaHistorialAtendidos historialShared) {
        initComponents();
        this.menuPrincipal = menuShared;
        this.colaTriaje = colaShared;
        this.historialAtendidos = historialShared;
        configurarValidaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscarPaciente = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        lblResultadoDetalle = new javax.swing.JLabel();
        lblResultadoNombre = new javax.swing.JLabel();
        lblResultadoCedula = new javax.swing.JLabel();
        txtBusquedaCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        btnBuscarPaciente.setBorder(null);
        btnBuscarPaciente.setContentAreaFilled(false);
        btnBuscarPaciente.addActionListener(this::btnBuscarPacienteActionPerformed);

        btnVolverMenu.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnVolverMenu.setActionCommand("");
        btnVolverMenu.setBorder(null);
        btnVolverMenu.setContentAreaFilled(false);
        btnVolverMenu.addActionListener(this::btnVolverMenuActionPerformed);

        txtBusquedaCedula.setBorder(null);
        txtBusquedaCedula.addActionListener(this::txtBusquedaCedulaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(txtBusquedaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblResultadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lblResultadoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblResultadoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(txtBusquedaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 990, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo_BusquedaPaciente.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1010, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarValidaciones() {

        // txtBusquedaCedula: unicamente digitos numericos, maximo 10 caracteres
        ((AbstractDocument) txtBusquedaCedula.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string == null) {
                    return;
                }
                String textoFiltrado = string.replaceAll("[^0-9]", "");
                int espacioDisponible = 10 - fb.getDocument().getLength();
                if (espacioDisponible <= 0) {
                    return;
                }
                if (textoFiltrado.length() > espacioDisponible) {
                    textoFiltrado = textoFiltrado.substring(0, espacioDisponible);
                }
                super.insertString(fb, offset, textoFiltrado, attr);
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text == null) {
                    super.replace(fb, offset, length, text, attrs);
                    return;
                }
                String textoFiltrado = text.replaceAll("[^0-9]", "");
                int espacioDisponible = 10 - (fb.getDocument().getLength() - length);
                if (espacioDisponible < 0) {
                    espacioDisponible = 0;
                }
                if (textoFiltrado.length() > espacioDisponible) {
                    textoFiltrado = textoFiltrado.substring(0, espacioDisponible);
                }
                super.replace(fb, offset, length, textoFiltrado, attrs);
            }
        });
    }
    
    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:
        this.menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
       // TODO add your handling code here:                                                                                                 
    String cedulaBuscada = txtBusquedaCedula.getText().trim();

    // 1. Limpiamos los resultados anteriores por si acaso
    lblResultadoNombre.setText("");
    lblResultadoDetalle.setText("");
    lblResultadoDetalle.setText("");

    if (cedulaBuscada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de cédula para buscar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validación: la cédula debe contener exactamente 10 dígitos numéricos
    if (!cedulaBuscada.matches("[0-9]{10}")) {
        JOptionPane.showMessageDialog(this, "La cédula debe contener exactamente 10 dígitos numéricos.", "Cédula Inválida", JOptionPane.WARNING_MESSAGE);
        return;
    }

    GestorAlgoritmos gestor = new GestorAlgoritmos();

    // -------------------------------------------------------------------------
    // FASE 1: Buscar en la Cola de Espera (Pacientes sin atender)
    // -------------------------------------------------------------------------
    Paciente[] enEspera = colaTriaje.transformarAArreglo();
    if (enEspera.length > 0) {
        // Ordenamiento por Merge Sort recursivo
        gestor.ordenarHistorialRecursivo(enEspera, 0, enEspera.length - 1);
        // Búsqueda Binaria de alta eficiencia O(log n)
        Paciente encontradoEspera = gestor.buscarPacienteBinario(enEspera, cedulaBuscada, 0, enEspera.length - 1);
        
        if (encontradoEspera != null) {
            // Pintamos los datos en tus JLabels debajo del título
            lblResultadoNombre.setText("Paciente: " + encontradoEspera.getNombre());
            lblResultadoDetalle.setText("Estado: EN LISTA DE ESPERA (Fila de Triaje)");
            lblResultadoDetalle.setText("Prioridad: Nivel " + encontradoEspera.getNivelTriaje() + " - Aguarde el llamado.");
            return; 
        }
    }

    // -------------------------------------------------------------------------
    // FASE 2: Buscar en el Historial de Atendidos
    // -------------------------------------------------------------------------
    Paciente[] enHistorial = historialAtendidos.obtenerHistorialComoArreglo();
    if (enHistorial.length > 0) {
        // Ordenamiento y búsqueda binaria sobre el historial
        gestor.ordenarHistorialRecursivo(enHistorial, 0, enHistorial.length - 1);
        Paciente encontradoHistorial = gestor.buscarPacienteBinario(enHistorial, cedulaBuscada, 0, enHistorial.length - 1);
        
        if (encontradoHistorial != null) {
            // Pintamos los datos correspondientes en el historial
            lblResultadoNombre.setText("Paciente: " + encontradoHistorial.getNombre());
            lblResultadoDetalle.setText("Estado: YA ATENDIDO");
            lblResultadoDetalle.setText("Detalle: El paciente ya fue llamado por el médico de turno.");
            return;
        }
    }

    // -------------------------------------------------------------------------
    // FASE 3: No existe en el sistema
    // -------------------------------------------------------------------------
    lblResultadoNombre.setText("No se encontraron registros.");
    lblResultadoDetalle.setText("La cédula '" + cedulaBuscada + "' no coincide con ningún paciente de hoy.");
    lblResultadoDetalle.setText("");
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void txtBusquedaCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaCedulaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResultadoCedula;
    private javax.swing.JLabel lblResultadoDetalle;
    private javax.swing.JLabel lblResultadoNombre;
    private javax.swing.JTextField txtBusquedaCedula;
    // End of variables declaration//GEN-END:variables
}
